spring:
  profiles:
    active: "default"
  main:
    banner-mode: "off"
server:
  port: 8080
configuration:
  version: 1.0-SNAPSHOT
  storageMountPath: "${TURING_DUMP_PVC_MOUNT_PATH}"
  dmpFileExtension: ".dmp"
  logFileExtension: ".log"
---
spring:
  profiles: local-dev
server:
  port: 8081
configuration:
  storageMountPath: "/tmp/turing/odump"
---
spring:
  profiles: local-docker
configuration:
  storageMountPath: "/tmp/turing/odump"